name: IoT Infra Terraform CI/CD

on:
  push:
    branches: [ "main", "dev", "prod" ]
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [ dev, prod ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform FMT
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform -chdir=terraform/${{ matrix.environment }} init

      - name: Terraform Validate
        run: terraform -chdir=terraform/${{ matrix.environment }} validate

      - name: Terraform Plan
        run: terraform -chdir=terraform/${{ matrix.environment }} plan

      - name: Terraform Apply
        if: (github.ref == 'refs/heads/dev' && matrix.environment == 'dev') || (github.ref == 'refs/heads/prod' && matrix.environment == 'prod')
        run: terraform -chdir=terraform/${{ matrix.environment }} apply -auto-approve

