name: Terraform CI/CD for Lambda SNS

on:
  push:
    branches: [ "main", "dev", "prod" ]
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [ dev, prod ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform FMT
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform -chdir=terraform/${{ matrix.environment }} init

      - name: Terraform Validate
        run: terraform -chdir=terraform/${{ matrix.environment }} validate

      - name: Terraform Plan
        run: terraform -chdir=terraform/${{ matrix.environment }} plan

      - name: Terraform Apply (only prod/dev branch)
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/prod'
        run: terraform -chdir=terraform/${{ matrix.environment }} apply -auto-approve
        env:
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  